#!/usr/bin/env node
/**
 * generate-key.js — Sign a license key for a customer.
 *
 * Usage:
 *   node scripts/generate-key.js <customer_id> [tier] [days]
 *
 * Examples:
 *   node scripts/generate-key.js customer_001 basic 30
 *   node scripts/generate-key.js customer_002 pro 30
 *   node scripts/generate-key.js customer_003 pro 60
 *
 * Requires:
 *   keys/private.key  (generated by generate-rsa-keys.js)
 */

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const PRIVATE_KEY_PATH = path.join(__dirname, "..", "keys", "private.key");

function signLicense(customerId, tier, days) {
  if (!fs.existsSync(PRIVATE_KEY_PATH)) {
    console.error("Private key not found. Run 'node scripts/generate-rsa-keys.js' first.");
    process.exit(1);
  }

  const privateKey = fs.readFileSync(PRIVATE_KEY_PATH, "utf-8");

  const nowMs = Date.now();
  const expMs = nowMs + days * 24 * 60 * 60 * 1000;
  const exp = Math.floor(expMs / 1000);

  const payload = JSON.stringify({
    cid: customerId,
    exp: exp,
    tier: tier,
  });

  const signature = crypto.sign("sha256", Buffer.from(payload), privateKey);

  const key =
    Buffer.from(payload, "utf-8").toString("base64url") +
    "." +
    signature.toString("base64url");

  console.log("License Key Generated");
  console.log("=====================");
  console.log("Customer:   " + customerId);
  console.log("Tier:       " + tier);
  console.log("Expires:    " + new Date(expMs).toISOString());
  console.log("Days:       " + days);
  console.log("");
  console.log("Key (copy this and send to customer):");
  console.log(key);
  console.log("");
}

function main() {
  const customerId = process.argv[2];
  const tier = process.argv[3] || "basic";
  const days = parseInt(process.argv[4] || "30", 10);

  if (!customerId) {
    console.error("Usage: node scripts/generate-key.js <customer_id> [tier] [days]");
    console.error("  tier: basic | pro  (default: basic)");
    console.error("  days: number       (default: 30)");
    process.exit(1);
  }

  if (tier !== "basic" && tier !== "pro") {
    console.error("Tier must be 'basic' or 'pro'");
    process.exit(1);
  }

  if (isNaN(days) || days < 1) {
    console.error("Days must be a positive number");
    process.exit(1);
  }

  signLicense(customerId, tier, days);
}

main();
