#!/usr/bin/env node
/**
 * generate-key.js — Sign a device-bound license key for a customer.
 *
 * Usage:
 *   node scripts/generate-key.js <customer_id> <tier> <days> --fp <fingerprint>
 *
 * Examples:
 *   node scripts/generate-key.js customer_001 basic 30 --fp abc123def456...
 *   node scripts/generate-key.js customer_002 pro 30 --fp def789abc012...
 *
 * IMPORTANT: The fingerprint MUST come from the customer's device.
 *            Ask them to open the extension popup and copy their fingerprint.
 *
 * Requires:
 *   keys/private.key  (generated by generate-rsa-keys.js)
 */

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const PRIVATE_KEY_PATH = path.join(__dirname, "..", "keys", "private.key");

function signLicense(customerId, tier, days, deviceFp) {
  if (!fs.existsSync(PRIVATE_KEY_PATH)) {
    console.error("Private key not found. Run 'node scripts/generate-rsa-keys.js' first.");
    process.exit(1);
  }

  const privateKey = fs.readFileSync(PRIVATE_KEY_PATH, "utf-8");

  const nowMs = Date.now();
  const expMs = nowMs + days * 24 * 60 * 60 * 1000;
  const exp = Math.floor(expMs / 1000);

  const payloadObj = {
    cid: customerId,
    exp: exp,
    tier: tier,
    fp: deviceFp,   // ← REQUIRED: device fingerprint, cryptographically bound
  };

  const payload = JSON.stringify(payloadObj);

  const signature = crypto.sign("sha256", Buffer.from(payload), privateKey);

  const key =
    Buffer.from(payload, "utf-8").toString("base64url") +
    "." +
    signature.toString("base64url");

  console.log("License Key Generated");
  console.log("=====================");
  console.log("Customer:   " + customerId);
  console.log("Tier:       " + tier);
  console.log("Expires:    " + new Date(expMs).toISOString());
  console.log("Days:       " + days);
  console.log("Device FP:  " + deviceFp.substring(0, 16) + "... (LOCKED)");
  console.log("");
  console.log("Key (copy this and send to customer):");
  console.log(key);
  console.log("");
}

function main() {
  const args = process.argv.slice(2);

  // Parse --fp flag (REQUIRED)
  let deviceFp = null;
  const fpIndex = args.indexOf("--fp");
  if (fpIndex !== -1 && args[fpIndex + 1]) {
    deviceFp = args[fpIndex + 1];
    args.splice(fpIndex, 2);
  }

  const customerId = args[0];
  const tier = args[1] || "basic";
  const days = parseInt(args[2] || "30", 10);

  if (!customerId) {
    console.error("Usage: node scripts/generate-key.js <customer_id> <tier> <days> --fp <fingerprint>");
    console.error("  tier: basic | pro");
    console.error("  days: number");
    console.error("  --fp: device fingerprint (REQUIRED — ask customer to copy from extension popup)");
    process.exit(1);
  }

  if (!deviceFp) {
    console.error("❌ ERROR: --fp <fingerprint> is REQUIRED.");
    console.error("   Ask your customer to open the extension popup and copy their device fingerprint.");
    console.error("   Then run: node scripts/generate-key.js " + customerId + " " + tier + " " + days + " --fp <their-fingerprint>");
    process.exit(1);
  }

  if (tier !== "basic" && tier !== "pro") {
    console.error("Tier must be 'basic' or 'pro'");
    process.exit(1);
  }

  if (isNaN(days) || days < 1) {
    console.error("Days must be a positive number");
    process.exit(1);
  }

  signLicense(customerId, tier, days, deviceFp);
}

main();
